name: Deploy Hasura Project to cloud

# on:
#   push:
#     branches: ["main"]
on: workflow_dispatch

jobs:
  deploy-hasura-cloud:
    name: Sync Hasura Metadata and Migrations
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: Install Hasura CLI
        run:  curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
        # version v2.40.0 is the latest version as of now just adding this line for consistency
      - name: Update Hasura CLI
        run: sudo hasura update-cli --version v2.40.0
      - name: 'Create env file'
        run: |
          touch hasura-metadata/.env
          echo "${{ secrets.HASURA_CLOUD_ENV }}" >> hasura-metadata/.env
      - name: Update Metadata and Migrations
        working-directory: hasura-metadata
        run: |
          hasura migrate apply --database-name "Test DB"
          hasura metadata apply
